services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
        VITE_SOCKET_URL: http://localhost:8000
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "3000:80"
    depends_on:
      - backend
